# Generated by Django 4.2.7 on 2026-01-15 00:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('goal_text', models.TextField(help_text="User's study goal description")),
                ('deadline', models.DateField(blank=True, help_text='Optional deadline for the goal', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text="Whether this is the user's current active plan")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlanVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField(default=1)),
                ('content_json', models.JSONField(help_text='Structured plan content: weekly roadmap, daily tasks, topics, resources, checkpoints')),
                ('prompt_used', models.TextField(help_text='The prompt sent to OpenAI')),
                ('model_used', models.CharField(default='gpt-4-turbo-preview', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='plans.plan')),
            ],
            options={
                'db_table': 'plan_versions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['plan', '-created_at'], name='plan_versio_plan_id_583cb8_idx')],
                'unique_together': {('plan', 'version_number')},
            },
        ),
        migrations.AddIndex(
            model_name='plan',
            index=models.Index(fields=['user', '-created_at'], name='plans_user_id_705d7a_idx'),
        ),
    ]
